version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
